### ISSUE TITLE
Missing list of dependencies (minor)

### ISSUE THREAD

**Issue by fakub** [SNUCP/MKTFHE#1]
To make the demo run, the following dependencies must be installed / run in julia shell:

    import Pkg
    Pkg.add("GenericFFT")
    Pkg.add("DarkIntegers")
    Pkg.add("DoubleFloats")

Would be nice to have this in README, otherwise the code fails with the first try.

**Comment by SNUPrivacyShared** [comment]
Thank you. We updated the README file.
